# Generated by Django 3.2.10 on 2021-12-29 15:44

from django.db import migrations, models
import django.utils.timezone
import utility.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', utility.db_fields.TableNamePKField(blank=True, default=None, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('org_id', models.IntegerField(db_index=True, default=1, verbose_name='组织ID')),
                ('biz_id', models.IntegerField(db_index=True, default=1, verbose_name='业务ID')),
                ('src_id', models.IntegerField(db_index=True, default=1, verbose_name='数据源ID')),
                ('sn', models.CharField(blank=True, db_index=True, help_text='SN', max_length=128, null=True, verbose_name='SN')),
                ('sdk_name', models.CharField(db_index=True, default='amap', help_text='定位组件名称', max_length=32, verbose_name='定位组件名称')),
                ('coordinate_name', models.CharField(db_index=True, default='GCJ02', help_text='坐标系名称', max_length=32, verbose_name='坐标系名称')),
                ('longitude', models.FloatField(blank=True, db_index=True, help_text='经度 idx', null=True, verbose_name='经度')),
                ('latitude', models.FloatField(blank=True, db_index=True, help_text='纬度 idx', null=True, verbose_name='纬度')),
                ('radius', models.FloatField(blank=True, db_index=True, help_text='半径 idx', null=True, verbose_name='半径')),
                ('altitude', models.FloatField(blank=True, db_index=True, help_text='海拔 idx', null=True, verbose_name='海拔')),
                ('direction', models.FloatField(blank=True, db_index=True, help_text='方向角', null=True, verbose_name='方向角')),
                ('velocity', models.FloatField(blank=True, db_index=True, help_text='速度', null=True, verbose_name='速度')),
                ('acceleration', models.FloatField(blank=True, db_index=True, help_text='加速度', null=True, verbose_name='加速度')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='服务器时间', verbose_name='服务器时间')),
                ('client_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='客户端时间', verbose_name='客户端时间')),
                ('field_01', models.CharField(blank=True, db_index=True, help_text='idx', max_length=128, null=True, verbose_name='Field 01')),
                ('field_02', models.CharField(blank=True, db_index=True, help_text='idx', max_length=128, null=True, verbose_name='Field 02')),
                ('field_03', models.CharField(blank=True, db_index=True, help_text='idx', max_length=128, null=True, verbose_name='Field 03')),
                ('text_01', models.TextField(blank=True, null=True, verbose_name='Text_01')),
            ],
            options={
                'verbose_name': '01.地图标记信息',
                'verbose_name_plural': '01.地图标记信息',
                'ordering': ['-create_time'],
            },
        ),
    ]
