# Generated by Django 3.2.11 on 2022-01-19 11:10

from django.db import migrations
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0002_alter_point_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='id',
            field=utility.db_fields.TableNamePKField(blank=True, default=utility.db_fields.TableNamePKField.auto_id, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
