# Generated by Django 3.2.11 on 2022-02-15 14:59

from django.db import migrations
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0003_alter_point_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='id',
            field=utility.db_fields.TableNamePKField('point', serialize=False),
        ),
    ]
