# Generated by Django 3.2.11 on 2023-09-22 11:27

from django.db import migrations, models
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0004_alter_point_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polygon',
            fields=[
                ('id', utility.db_fields.TableNamePKField('point', editable=False, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('org_id', models.IntegerField(db_index=True, default=1, verbose_name='组织ID')),
                ('biz_id', models.IntegerField(db_index=True, default=1, verbose_name='业务ID')),
                ('src_id', models.IntegerField(db_index=True, default=1, verbose_name='数据源ID')),
                ('sn', models.CharField(blank=True, db_index=True, help_text='SN', max_length=128, null=True, verbose_name='SN')),
                ('coordinate_name', models.CharField(db_index=True, default='GCJ02', help_text='坐标系名称', max_length=32, verbose_name='坐标系名称')),
                ('line', models.TextField(blank=True, help_text='多边形坐标', null=True, verbose_name='多边形坐标')),
                ('line_style', models.TextField(blank=True, help_text='多边形样式', null=True, verbose_name='多边形样式')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, help_text='服务器时间', verbose_name='服务器时间')),
                ('field_01', models.CharField(blank=True, db_index=True, help_text='idx', max_length=128, null=True, verbose_name='Field 01')),
                ('field_02', models.CharField(blank=True, db_index=True, help_text='idx', max_length=128, null=True, verbose_name='Field 02')),
                ('field_03', models.CharField(blank=True, db_index=True, help_text='idx', max_length=128, null=True, verbose_name='Field 03')),
                ('text_01', models.TextField(blank=True, null=True, verbose_name='Text_01')),
            ],
            options={
                'verbose_name': '02.地图多边形信息',
                'verbose_name_plural': '02.地图多边形信息',
                'ordering': ['-create_time'],
            },
        ),
    ]
