# Generated by Django 3.2.11 on 2023-09-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0005_polygon'),
    ]

    operations = [
        migrations.AddField(
            model_name='point',
            name='category',
            field=models.CharField(blank=True, db_index=True, help_text='类别 idx', max_length=128, null=True, verbose_name='类别'),
        ),
        migrations.AddField(
            model_name='polygon',
            name='category',
            field=models.CharField(blank=True, db_index=True, help_text='类别 idx', max_length=128, null=True, verbose_name='类别'),
        ),
    ]
