# Generated by Django 4.2.8 on 2024-01-30 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0006_auto_20230922_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='point',
            name='latitude',
            field=models.CharField(blank=True, db_index=True, help_text='纬度 idx', max_length=32, null=True, verbose_name='纬度'),
        ),
        migrations.AlterField(
            model_name='point',
            name='longitude',
            field=models.CharField(blank=True, db_index=True, help_text='经度 idx', max_length=32, null=True, verbose_name='经度'),
        ),
    ]
