# Generated by Django 3.2.10 on 2021-12-29 15:44

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import utility.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseTree',
            fields=[
                ('id', utility.db_fields.TableNamePKField(blank=True, default=None, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('org_id', models.IntegerField(db_index=True, default=1, verbose_name='组织ID')),
                ('biz_id', models.IntegerField(db_index=True, default=1, verbose_name='业务ID')),
                ('src_id', models.IntegerField(db_index=True, default=1, verbose_name='数据源ID')),
                ('name', models.CharField(blank=True, help_text='类别名称', max_length=255, null=True, verbose_name='类别名称')),
                ('description', models.TextField(blank=True, help_text='说明', null=True, verbose_name='说明')),
                ('arguments', models.TextField(blank=True, help_text='参数', null=True, verbose_name='参数')),
                ('icon', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Icon')),
                ('field_01', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Field 01')),
                ('field_02', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Field 02')),
                ('field_03', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Field 03')),
                ('int_01', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Int 01')),
                ('float_01', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Float 01')),
                ('text_01', models.TextField(blank=True, null=True, verbose_name='Text_01')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='上级ID parent_id to baseconfig_basetree', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='baseconfig.basetree', verbose_name='上级')),
            ],
            options={
                'verbose_name': '分类树',
                'verbose_name_plural': '分类树',
            },
        ),
        migrations.CreateModel(
            name='BaseConfigFileUpload',
            fields=[
                ('id', utility.db_fields.TableNamePKField(blank=True, default=None, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('org_id', models.IntegerField(db_index=True, default=1, verbose_name='组织ID')),
                ('biz_id', models.IntegerField(db_index=True, default=1, verbose_name='业务ID')),
                ('src_id', models.IntegerField(db_index=True, default=1, verbose_name='数据源ID')),
                ('file', models.FileField(help_text='文件', upload_to='baseconfigvaluefile/%Y/%m/%d/', verbose_name='文件')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(blank=True, db_constraint=False, help_text='分类', null=True, on_delete=django.db.models.deletion.SET_NULL, to='baseconfig.basetree')),
            ],
            options={
                'verbose_name': '基础配置项文件',
                'verbose_name_plural': '基础配置项文件',
                'ordering': ['pk'],
            },
        ),
    ]
