# Generated by Django 3.2.10 on 2022-01-06 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basetree',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
