# Generated by Django 3.2.11 on 2022-12-07 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseconfig', '0005_auto_20220215_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseconfigfileupload',
            name='file_name',
            field=models.CharField(blank=True, help_text='文件名称', max_length=1023, null=True, verbose_name='文件名'),
        ),
    ]
