# Generated by Django 3.2.11 on 2022-12-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseconfig', '0006_baseconfigfileupload_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseconfigfileupload',
            name='obj_id',
            field=models.CharField(blank=True, db_index=True, help_text='关联对象ID', max_length=64, null=True, verbose_name='关联对象ID'),
        ),
    ]
