# Generated by Django 3.2.11 on 2023-09-04 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseconfig', '0007_baseconfigfileupload_obj_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseconfigfileupload',
            name='file',
            field=models.FileField(help_text='文件', max_length=1023, upload_to='baseconfigvaluefile/%Y/%m/%d/', verbose_name='文件'),
        ),
    ]
