# Generated by Django 3.2.11 on 2023-10-17 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formtemplate', '0011_auto_20230829_1504'),
        ('baseconfig', '0009_baseconfigfileupload_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseconfigfileupload',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='用户', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='baseconfigfileupload',
            name='template',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='模板', null=True, on_delete=django.db.models.deletion.CASCADE, to='formtemplate.formtemplate'),
        ),
    ]
