# Generated by Django 4.2.8 on 2024-07-24 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseconfig', '0010_auto_20231017_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseconfigfileupload',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='是否删除'),
        ),
    ]
