# Generated by Django 4.2.16 on 2025-04-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseconfig', '0011_baseconfigfileupload_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseconfigfileupload',
            name='dify_document_id',
            field=models.CharField(blank=True, db_index=True, help_text='Dify文档ID', max_length=36, null=True, verbose_name='Dify文档ID'),
        ),
    ]
