# Generated by Django 3.2.10 on 2022-01-06 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_goods_obj_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='lng',
        ),
        migrations.AddField(
            model_name='goods',
            name='altitude',
            field=models.FloatField(blank=True, help_text='海拔 idx', null=True, verbose_name='海拔'),
        ),
        migrations.AddField(
            model_name='goods',
            name='latitude',
            field=models.FloatField(blank=True, help_text='纬度 idx', null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='goods',
            name='longitude',
            field=models.FloatField(blank=True, help_text='经度 idx', null=True, verbose_name='经度'),
        ),
    ]
