# Generated by Django 3.2.11 on 2022-01-19 11:10

from django.db import migrations, models
import django.db.models.deletion
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('goods', '0005_alter_goods_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='obj_type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='外键字段类型', null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='id',
            field=utility.db_fields.TableNamePKField(blank=True, default=utility.db_fields.TableNamePKField.auto_id, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
