# Generated by Django 3.2.11 on 2022-07-15 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_auto_20220120_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='父级ID必须是本表', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='goods.goods'),
        ),
    ]
