# Generated by Django 3.2.10 on 2021-12-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now=True, help_text='创建时间', verbose_name='创建时间'),
        ),
    ]
