# Generated by Django 3.2.11 on 2022-02-15 14:58

from django.db import migrations
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0006_auto_20220215_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=utility.db_fields.TableNamePKField('dep', serialize=False),
        ),
        migrations.AlterField(
            model_name='funcgroup',
            name='id',
            field=utility.db_fields.TableNamePKField('group', serialize=False),
        ),
        migrations.AlterField(
            model_name='funcpermission',
            name='id',
            field=utility.db_fields.TableNamePKField('perm', serialize=False),
        ),
        migrations.AlterField(
            model_name='phoneaccess',
            name='id',
            field=utility.db_fields.TableNamePKField('pa', serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=utility.db_fields.TableNamePKField('user', serialize=False),
        ),
    ]
