# Generated by Django 3.2.11 on 2022-04-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0008_user_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcgroup',
            name='sort_num',
            field=models.IntegerField(blank=True, db_index=True, default=0, help_text='排序编号', null=True, verbose_name='排序编号'),
        ),
    ]
