# Generated by Django 3.2.11 on 2022-04-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0010_user_data_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_permission',
            field=models.CharField(blank=True, choices=[('仅自己', '仅自己'), ('本部门', '本部门'), ('全部', '全部')], help_text='数据范围', max_length=32, null=True, verbose_name='数据范围'),
        ),
    ]
