# Generated by Django 3.2.11 on 2022-04-28 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0011_alter_user_data_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcgroup',
            name='name',
            field=models.CharField(max_length=150, verbose_name='角色名称'),
        ),
    ]
