# Generated by Django 3.2.11 on 2022-08-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0012_alter_funcgroup_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_department_manager',
            field=models.BooleanField(default=False, help_text='部门主管', verbose_name='部门主管'),
        ),
    ]
