# Generated by Django 3.2.11 on 2022-09-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0013_user_is_department_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.TextField(blank=True, help_text='头像URL', null=True, verbose_name='头像URL'),
        ),
    ]
