# Generated by Django 3.2.11 on 2022-09-08 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0014_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_leader',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='部门分管领导', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
