# Generated by Django 3.2.11 on 2022-09-15 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0015_department_head_leader'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sign_file',
            field=models.TextField(blank=True, help_text='签名URL', null=True, verbose_name='签名URL'),
        ),
    ]
