# Generated by Django 3.2.11 on 2022-12-26 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0016_user_sign_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcgroup',
            name='biz_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='业务ID'),
        ),
    ]
