# Generated by Django 3.2.10 on 2023-02-14 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0017_funcgroup_biz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcpermission',
            name='biz_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='业务ID'),
        ),
    ]
