# Generated by Django 3.2.11 on 2023-07-20 12:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0018_funcpermission_biz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='dep_manager',
            field=models.ManyToManyField(blank=True, db_constraint=False, help_text='部门主管', related_name='dep_manager', to=settings.AUTH_USER_MODEL),
        ),
    ]
