# Generated by Django 3.2.11 on 2023-09-18 15:19

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0019_department_dep_manager'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='funcpermission',
            options={'ordering': ('name',), 'verbose_name': '04.功能权限', 'verbose_name_plural': '04.功能权限'},
        ),
        migrations.AddField(
            model_name='funcpermission',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcpermission',
            name='lft',
            field=models.PositiveIntegerField(default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcpermission',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, help_text='parent_id to usercenter_funcpermission', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='usercenter.funcpermission', verbose_name='上级'),
        ),
        migrations.AddField(
            model_name='funcpermission',
            name='rght',
            field=models.PositiveIntegerField(default=2, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcpermission',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='funcpermission',
            name='codename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='代码'),
        ),
    ]
