# Generated by Django 3.2.11 on 2023-10-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0020_auto_20230918_1519'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_date',
            field=models.DateTimeField(blank=True, help_text='密码修改时间', null=True, verbose_name='密码修改时间'),
        ),
    ]
