# Generated by Django 4.2.8 on 2024-08-27 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0021_user_password_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='data_permission',
            field=models.CharField(blank=True, choices=[('仅自己', '仅自己'), ('本部门', '本部门'), ('本部门及下级', '本部门及下级'), ('全部', '全部')], help_text='数据范围', max_length=32, null=True, verbose_name='数据范围'),
        ),
    ]
