# Generated by Django 4.2.8 on 2024-09-13 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0022_alter_user_data_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcpermission',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='funcpermission',
            name='codename',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='说明'),
        ),
    ]
