# Generated by Django 4.2.16 on 2025-03-26 11:32

from django.db import migrations, models
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0023_funcpermission_creator_alter_funcpermission_codename'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccess',
            fields=[
                ('id', utility.db_fields.TableNamePKField('ea', editable=False, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('org_id', models.IntegerField(db_index=True, default=1, verbose_name='组织ID')),
                ('email', models.EmailField(help_text='邮箱', max_length=255, verbose_name='邮箱')),
                ('email_access', models.CharField(help_text='验证码', max_length=10, verbose_name='验证码')),
                ('create_time', models.DateTimeField(auto_now=True, db_index=True, help_text='发送时间', verbose_name='发送时间')),
            ],
            options={
                'verbose_name': '06.邮箱验证码',
                'verbose_name_plural': '06.邮箱验证码',
                'ordering': ['-create_time'],
            },
        ),
    ]
