# Generated by Django 3.2.10 on 2021-12-29 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import system.models
import utility.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usercenter', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', utility.db_fields.TableNamePKField(blank=True, default=None, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, unique=True, verbose_name='系统ID')),
                ('name', models.CharField(help_text='系统名称', max_length=256, verbose_name='系统名称')),
                ('url', models.CharField(blank=True, help_text='线上地址', max_length=256, null=True, verbose_name='线上地址')),
                ('description', models.TextField(blank=True, help_text='系统说明', null=True, verbose_name='系统说明')),
                ('multi_org', models.BooleanField(default=False, help_text='多租户系统', verbose_name='多租户系统')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': '系统',
                'verbose_name_plural': '系统',
            },
        ),
        migrations.CreateModel(
            name='WechatConfig',
            fields=[
                ('id', utility.db_fields.TableNamePKField(blank=True, default=None, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('is_default', models.BooleanField(default=True, help_text='是否默认', verbose_name='是否默认')),
                ('mp_name', models.CharField(blank=True, help_text='微信公众号名称', max_length=64, null=True, verbose_name='微信公众号名称')),
                ('mp_aid', models.CharField(blank=True, db_index=True, help_text='微信公众号AppID', max_length=64, null=True, verbose_name='微信公众号AppID')),
                ('mp_sk', models.CharField(blank=True, db_index=True, help_text='微信公众号AppSecret', max_length=128, null=True, verbose_name='微信公众号AppSecret')),
                ('wxa_name', models.CharField(blank=True, help_text='微信小程序名称', max_length=64, null=True, verbose_name='微信小程序名称')),
                ('wxa_aid', models.CharField(blank=True, db_index=True, help_text='微信小程序AppID', max_length=64, null=True, verbose_name='微信小程序AppID')),
                ('wxa_sk', models.CharField(blank=True, db_index=True, help_text='微信小程序AppSecret', max_length=128, null=True, verbose_name='微信小程序AppSecret')),
                ('mch_api_key', models.CharField(blank=True, db_index=True, help_text='微信支付商户key', max_length=32, null=True, verbose_name='微信支付商户key')),
                ('mch_id', models.CharField(blank=True, db_index=True, help_text='微信支付商户号', max_length=32, null=True, verbose_name='微信支付商户号')),
                ('mch_sub_id', models.CharField(blank=True, db_index=True, help_text='微信支付子商户号', max_length=32, null=True, verbose_name='微信支付子商户号')),
                ('mch_cert', models.CharField(blank=True, db_index=True, help_text='微信支付商户证书路径', max_length=256, null=True, verbose_name='微信支付商户证书路径')),
                ('mch_key', models.CharField(blank=True, db_index=True, help_text='微信支付商户证书私钥路径', max_length=256, null=True, verbose_name='微信支付商户证书私钥路径')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('system', models.ForeignKey(help_text='系统ID', on_delete=django.db.models.deletion.CASCADE, related_name='wechatconfig', to='system.system', verbose_name='系统ID')),
            ],
            options={
                'verbose_name': '系统微信相关配置',
                'verbose_name_plural': '系统微信相关配置',
            },
        ),
        migrations.CreateModel(
            name='SystemProject',
            fields=[
                ('id', utility.db_fields.TableNamePKField(blank=True, default=None, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='项目名称', max_length=63, verbose_name='项目名称')),
                ('git_url', models.CharField(db_index=True, help_text='项目Git仓库地址(git remote url)', max_length=255, verbose_name='Git 地址')),
                ('project_type', models.CharField(choices=[('PC WEB', 'PC WEB'), ('微信小程序', '微信小程序'), ('公众号网页', '公众号网页'), ('移动端H5应用', '移动端H5应用'), ('uni-app', 'uni-app'), ('react-native', 'react-native'), ('Python CMS', 'Python CMS')], db_index=True, help_text='项目工程类型', max_length=31, verbose_name='项目工程类型')),
                ('desc', models.TextField(blank=True, help_text='说明', null=True, verbose_name='说明')),
                ('router_content', models.TextField(blank=True, help_text='路由内容', null=True, verbose_name='路由内容')),
                ('online_time', models.DateTimeField(blank=True, help_text='上线时间', null=True, verbose_name='上线时间')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(help_text='系统ID', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='system.system', verbose_name='系统ID')),
            ],
            options={
                'verbose_name': '系统项目工程配置',
                'verbose_name_plural': '系统项目工程配置',
            },
        ),
        migrations.CreateModel(
            name='SystemOrg',
            fields=[
                ('id', utility.db_fields.TableNamePKField(blank=True, default=None, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('org_id', models.IntegerField(db_index=True, default=system.models.next_org_id, verbose_name='租户ID')),
                ('src_id', models.IntegerField(db_index=True, default=1, verbose_name='数据源ID')),
                ('name', models.CharField(help_text='名称', max_length=256, verbose_name='名称')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('license', models.TextField(blank=True, help_text='证书内容', null=True, verbose_name='证书内容')),
                ('manager', models.ForeignKey(blank=True, db_constraint=False, help_text='管理员ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, db_constraint=False, help_text='通过中间表 system_systemorg_func_user_permissions 关联 usercenter_funcpermission', related_name='_system_systemorg_permissions_+', to='usercenter.FuncPermission', verbose_name='功能权限')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orgs', to='system.system', verbose_name='系统')),
            ],
            options={
                'verbose_name': '系统租户',
                'verbose_name_plural': '系统租户',
            },
        ),
        migrations.CreateModel(
            name='SystemModule',
            fields=[
                ('id', utility.db_fields.TableNamePKField(blank=True, default=None, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('name', models.CharField(help_text='模块名称', max_length=256, verbose_name='模块名称')),
                ('groups', models.ManyToManyField(blank=True, related_name='systemmodules', to='usercenter.FuncGroup', verbose_name='模块角色')),
                ('permissions', models.ManyToManyField(blank=True, related_name='systemmodules', to='usercenter.FuncPermission', verbose_name='模块权限')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='system.system', verbose_name='系统')),
            ],
            options={
                'verbose_name': '系统模块',
                'verbose_name_plural': '系统模块',
            },
        ),
        migrations.CreateModel(
            name='SMSConfig',
            fields=[
                ('id', utility.db_fields.TableNamePKField(blank=True, default=None, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, help_text='短信配置名称', max_length=128, null=True, verbose_name='短信配置名称')),
                ('sms_type', models.CharField(choices=[('JUHE', '聚合数据'), ('TENCENT', '腾讯云')], help_text='平台类型', max_length=32, verbose_name='平台类型')),
                ('is_enabled', models.BooleanField(default=True, help_text='是否启用', verbose_name='是否启用')),
                ('post_url', models.CharField(blank=True, help_text='发送接口URL', max_length=255, null=True, verbose_name='发送接口URL')),
                ('app_key', models.CharField(blank=True, help_text='App Key', max_length=128, null=True, verbose_name='App Key')),
                ('app_id', models.CharField(blank=True, help_text='App ID', max_length=128, null=True, verbose_name='App ID')),
                ('template_id', models.CharField(blank=True, help_text='短信模板ID', max_length=128, null=True, verbose_name='短信模板ID')),
                ('template_sign', models.CharField(blank=True, help_text='短信模板签名', max_length=128, null=True, verbose_name='短信模板签名')),
                ('tencent_cloud_appid', models.CharField(blank=True, help_text='腾讯云APPID', max_length=128, null=True, verbose_name='腾讯云APPID')),
                ('tencent_cloud_secretid', models.CharField(blank=True, help_text='腾讯云SECRETID', max_length=128, null=True, verbose_name='腾讯云SECRETID')),
                ('tencent_cloud_secretkey', models.CharField(blank=True, help_text='腾讯云SECRETKEY', max_length=128, null=True, verbose_name='腾讯云SECRETKEY')),
                ('system', models.ForeignKey(help_text='系统ID', on_delete=django.db.models.deletion.CASCADE, related_name='smsconfig', to='system.system', verbose_name='系统ID')),
            ],
            options={
                'verbose_name': '短信平台配置',
                'verbose_name_plural': '短信平台配置',
            },
        ),
    ]
