# Generated by Django 3.2.10 on 2021-12-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0001_initial'),
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='system', to='usercenter.FuncPermission', verbose_name='模块权限'),
        ),
        migrations.DeleteModel(
            name='SystemModule',
        ),
    ]
