# Generated by Django 3.2.10 on 2021-12-31 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('system', '0002_auto_20211229_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsconfig',
            name='system_org',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='系统租户ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smsconfig', to='system.systemorg', verbose_name='系统租户ID'),
        ),
        migrations.AddField(
            model_name='system',
            name='log_level',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], default=0, help_text='日志级别', verbose_name='日志级别'),
        ),
        migrations.AddField(
            model_name='wechatconfig',
            name='system_org',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='系统租户ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wechatconfig', to='system.systemorg', verbose_name='系统租户ID'),
        ),
        migrations.AlterField(
            model_name='smsconfig',
            name='system',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='系统ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='smsconfig', to='system.system', verbose_name='系统ID'),
        ),
        migrations.AlterField(
            model_name='wechatconfig',
            name='system',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='系统ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wechatconfig', to='system.system', verbose_name='系统ID'),
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', utility.db_fields.TableNamePKField(blank=True, default=None, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('org_id', models.IntegerField(db_index=True, default=1, editable=False, verbose_name='组织ID')),
                ('biz_id', models.IntegerField(db_index=True, default=1, verbose_name='业务ID')),
                ('src_id', models.IntegerField(db_index=True, default=1, verbose_name='数据源ID')),
                ('log_level', models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2')], default=0, help_text='日志级别', verbose_name='日志级别')),
                ('log_type', models.CharField(blank=True, help_text='日志类别', max_length=16, null=True, verbose_name='日志类别')),
                ('content', models.TextField(blank=True, help_text='日志内容', null=True, verbose_name='日志内容')),
                ('user_name', models.CharField(blank=True, help_text='操作用户名', max_length=64, null=True, verbose_name='操作用户名')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='User ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '系统日志',
                'verbose_name_plural': '系统日志',
            },
        ),
    ]
