# Generated by Django 3.2.11 on 2022-02-15 14:44

from django.db import migrations, models
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0006_auto_20220215_1444'),
        ('system', '0005_auto_20220119_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='permissions',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='system', to='usercenter.FuncPermission', verbose_name='模块权限'),
        )
    ]
