# Generated by Django 3.2.11 on 2022-04-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20220428_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='log_type',
            field=models.CharField(blank=True, db_index=True, help_text='日志类别', max_length=32, null=True, verbose_name='日志类别'),
        ),
    ]
