# Generated by Django 3.2.11 on 2022-12-05 15:01

from django.db import migrations, models
import django.db.models.deletion
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_alter_systemlog_log_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBiz',
            fields=[
                ('id', utility.db_fields.TableNamePKField('SYSBIZ', serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, verbose_name='系统ID')),
                ('biz_id', models.IntegerField(db_index=True, verbose_name='业务ID')),
                ('name', models.CharField(help_text='业务子系统名称', max_length=256, verbose_name='业务子系统名称')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bizs', to='system.system', verbose_name='系统')),
            ],
            options={
                'verbose_name': '业务子系统定义',
                'verbose_name_plural': '业务子系统定义',
            },
        ),
    ]
