# Generated by Django 3.2.11 on 2023-08-02 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0010_systembiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='allow_org_register',
            field=models.BooleanField(default=False, help_text='允许租户注册', verbose_name='允许租户注册'),
        ),
        migrations.AddField(
            model_name='system',
            name='default_org_validity_period',
            field=models.IntegerField(default=365, help_text='默认租户有效期', verbose_name='默认租户有效期'),
        ),
        migrations.AddField(
            model_name='system',
            name='is_long_time_validity_period',
            field=models.BooleanField(default=True, help_text='长期有效', verbose_name='长期有效'),
        ),
        migrations.AddField(
            model_name='systemorg',
            name='allow_user_register',
            field=models.BooleanField(default=False, help_text='允许用户注册', verbose_name='允许用户注册'),
        ),
    ]
