# Generated by Django 3.2.11 on 2023-08-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0019_department_dep_manager'),
        ('system', '0011_auto_20230802_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='default_org_permissions',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='_system_system_default_org_permissions_+', to='usercenter.FuncPermission', verbose_name='默认租户模块权限'),
        ),
        migrations.AddField(
            model_name='systemorg',
            name='is_disabled',
            field=models.BooleanField(default=False, help_text='是否禁用', verbose_name='是否禁用'),
        ),
    ]
