# Generated by Django 3.2.11 on 2023-08-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0012_auto_20230803_0953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemorg',
            name='allow_user_register',
            field=models.BooleanField(default=True, help_text='允许用户注册', verbose_name='允许用户注册'),
        ),
    ]
