# Generated by Django 3.2.11 on 2023-08-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0013_alter_systemorg_allow_user_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='industry',
            field=models.CharField(blank=True, help_text='行业', max_length=256, null=True, verbose_name='行业'),
        ),
    ]
