# Generated by Django 3.2.11 on 2023-08-16 18:12

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0014_system_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemProjectRouter',
            fields=[
                ('id', utility.db_fields.TableNamePKField('SPR', editable=False, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('path', models.CharField(help_text='路由路径', max_length=255, verbose_name='路由路径')),
                ('title', models.CharField(blank=True, help_text='路由页面标题', max_length=63, null=True, verbose_name='路由页面标题')),
                ('name', models.CharField(help_text='路由名称', max_length=63, verbose_name='路由名称')),
                ('component', models.CharField(blank=True, help_text='路由组件', max_length=255, null=True, verbose_name='路由组件')),
                ('redirect', models.CharField(blank=True, help_text='路由重定向', max_length=255, null=True, verbose_name='路由重定向')),
                ('props', models.BooleanField(default=False, help_text='路由传参', verbose_name='路由传参')),
                ('alias', models.CharField(blank=True, help_text='路由别名', max_length=1023, null=True, verbose_name='路由别名')),
                ('meta', models.TextField(blank=True, help_text='路由元信息', null=True, verbose_name='路由元信息')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system.systemprojectrouter')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routers', to='system.systemproject', verbose_name='项目ID')),
            ],
            options={
                'verbose_name': '系统项目工程路由配置',
                'verbose_name_plural': '系统项目工程路由配置',
            },
        ),
    ]
