# Generated by Django 3.2.11 on 2023-08-24 17:47

from django.db import migrations, models
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0015_systemprojectrouter'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemDataBackup',
            fields=[
                ('id', utility.db_fields.TableNamePKField('SYSDB', editable=False, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('org_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='组织ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('user_name', models.CharField(blank=True, help_text='操作用户名', max_length=64, null=True, verbose_name='操作用户名')),
                ('backup_params', models.TextField(blank=True, help_text='备份参数', null=True, verbose_name='备份参数')),
                ('backup_file', models.FileField(blank=True, help_text='备份文件', null=True, upload_to='system/data/backup', verbose_name='备份文件')),
            ],
            options={
                'verbose_name': '系统备份',
                'verbose_name_plural': '系统备份',
            },
        ),
    ]
