# Generated by Django 3.2.11 on 2023-09-19 18:15

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0020_auto_20230918_1519'),
        ('system', '0016_systemdatabackup'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemprojectrouter',
            name='permission',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='usercenter.funcpermission', verbose_name='路由权限'),
        ),
        migrations.CreateModel(
            name='SystemProjectMenu',
            fields=[
                ('id', utility.db_fields.TableNamePKField('SPM', editable=False, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('name', models.CharField(help_text='名称', max_length=63, verbose_name='名称')),
                ('icon', models.CharField(blank=True, help_text='图标', max_length=128, null=True, verbose_name='图标')),
                ('router_name', models.CharField(blank=True, help_text='路由名称', max_length=128, null=True, verbose_name='路由名称')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system.systemprojectmenu')),
                ('permission', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='usercenter.funcpermission', verbose_name='菜单权限')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='system.systemproject', verbose_name='项目ID')),
            ],
            options={
                'verbose_name': '系统项目工程菜单配置',
                'verbose_name_plural': '系统项目工程菜单配置',
            },
        ),
    ]
