# Generated by Django 3.2.11 on 2023-10-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0017_auto_20230919_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='need_reset_passwd',
            field=models.BooleanField(default=False, help_text='需要定时重置密码', verbose_name='需要定时重置密码'),
        ),
        migrations.AddField(
            model_name='system',
            name='reset_passwd_interval',
            field=models.IntegerField(help_text='重置密码周期', null=True, verbose_name='重置密码周期'),
        ),
    ]
