# Generated by Django 3.2.11 on 2023-10-27 17:48

from django.db import migrations, models
import django.db.models.deletion
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0018_auto_20231013_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='system',
            name='reset_passwd_interval',
            field=models.IntegerField(blank=True, help_text='重置密码周期', null=True, verbose_name='重置密码周期'),
        ),
        migrations.CreateModel(
            name='SMSLog',
            fields=[
                ('id', utility.db_fields.TableNamePKField('SMSL', editable=False, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('org_id', models.IntegerField(blank=True, help_text='租户ID', null=True, verbose_name='租户ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('expire_seconds', models.IntegerField(blank=True, help_text='超时时长', null=True, verbose_name='超时时长')),
                ('phone', models.CharField(help_text='手机号码', max_length=32, verbose_name='手机号码')),
                ('content', models.CharField(help_text='短信内容', max_length=255, verbose_name='短信内容')),
                ('sms_config', models.ForeignKey(blank=True, db_constraint=False, help_text='短信配置', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='system.smsconfig')),
            ],
            options={
                'verbose_name': '短信发送记录',
                'verbose_name_plural': '短信发送记录',
            },
        ),
    ]
