# Generated by Django 4.2.8 on 2024-01-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0021_user_password_date'),
        ('system', '0019_auto_20231027_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemproject',
            name='pm_name',
            field=models.CharField(blank=True, help_text='项目管理名称', max_length=63, null=True, verbose_name='项目管理名称'),
        ),
        migrations.AlterField(
            model_name='system',
            name='default_org_permissions',
            field=models.ManyToManyField(blank=True, db_constraint=False, related_name='+', to='usercenter.funcpermission', verbose_name='默认租户模块权限'),
        ),
        migrations.AlterField(
            model_name='systemorg',
            name='permissions',
            field=models.ManyToManyField(blank=True, db_constraint=False, help_text='通过中间表 system_systemorg_func_user_permissions 关联 usercenter_funcpermission', related_name='+', to='usercenter.funcpermission', verbose_name='功能权限'),
        ),
    ]
