# Generated by Django 4.2.8 on 2024-09-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0020_systemproject_pm_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemproject',
            name='biz_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='业务子系统ID', null=True, verbose_name='业务子系统ID'),
        ),
    ]
