# Generated by Django 4.2.8 on 2024-10-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0021_systemproject_biz_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemlog',
            name='template_id',
            field=models.CharField(blank=True, db_index=True, help_text='模板ID', max_length=32, null=True, verbose_name='模板ID'),
        ),
    ]
