# Generated by Django 4.2.16 on 2025-03-25 17:07

from django.db import migrations, models
import django.db.models.deletion
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0022_systemlog_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smsconfig',
            name='sms_type',
            field=models.CharField(choices=[('JUHE', '聚合数据'), ('TENCENT', '腾讯云'), ('JHSL', '景鸿商旅')], help_text='平台类型', max_length=32, verbose_name='平台类型'),
        ),
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', utility.db_fields.TableNamePKField('SYSEM', editable=False, serialize=False)),
                ('name', models.CharField(blank=True, help_text='邮件配置名称', max_length=128, null=True, verbose_name='邮件配置名称')),
                ('host', models.CharField(blank=True, help_text='邮件服务器', max_length=128, null=True, verbose_name='邮件服务器')),
                ('port', models.IntegerField(blank=True, help_text='邮件服务器端口', null=True, verbose_name='邮件服务器端口')),
                ('username', models.CharField(blank=True, help_text='邮件服务器用户名', max_length=128, null=True, verbose_name='邮件服务器用户名')),
                ('password', models.CharField(blank=True, help_text='邮件服务器密码', max_length=128, null=True, verbose_name='邮件服务器密码')),
                ('use_ssl', models.BooleanField(default=False, help_text='使用SSL', verbose_name='使用SSL')),
                ('use_tls', models.BooleanField(default=False, help_text='使用TLS', verbose_name='使用TLS')),
                ('from_email', models.EmailField(blank=True, help_text='发件人邮箱', max_length=254, null=True, verbose_name='发件人邮箱')),
                ('from_name', models.CharField(blank=True, help_text='发件人名称', max_length=128, null=True, verbose_name='发件人名称')),
                ('title_prefix', models.CharField(blank=True, help_text='标题前缀', max_length=128, null=True, verbose_name='标题前缀')),
                ('system', models.ForeignKey(blank=True, db_constraint=False, help_text='系统ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emailconfig', to='system.system', verbose_name='系统ID')),
                ('system_org', models.ForeignKey(blank=True, db_constraint=False, help_text='系统租户ID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emailconfig', to='system.systemorg', verbose_name='系统租户ID')),
            ],
            options={
                'verbose_name': '邮件平台配置',
                'verbose_name_plural': '邮件平台配置',
            },
        ),
    ]
