# Generated by Django 3.2.10 on 2021-12-29 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utility.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('article', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0001_initial'),
        ('usercenter', '0001_initial'),
        ('formtemplate', '0001_initial'),
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', utility.db_fields.TableNamePKField(blank=True, default=None, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('org_id', models.IntegerField(db_index=True, default=1, verbose_name='组织ID')),
                ('biz_id', models.IntegerField(db_index=True, default=1, verbose_name='业务ID')),
                ('src_id', models.IntegerField(db_index=True, default=1, verbose_name='数据源ID')),
                ('customera_name', models.CharField(blank=True, help_text='甲方名称', max_length=256, null=True, verbose_name='甲方名称')),
                ('customerb_name', models.CharField(blank=True, help_text='乙方名称', max_length=256, null=True, verbose_name='乙方名称')),
                ('customerc_name', models.CharField(blank=True, help_text='丙方名称', max_length=256, null=True, verbose_name='丙方名称')),
                ('orga_name', models.CharField(blank=True, help_text='甲方组织机构名称', max_length=256, null=True, verbose_name='甲方组织机构名称')),
                ('orgb_name', models.CharField(blank=True, help_text='乙方组织机构名称', max_length=256, null=True, verbose_name='乙方组织机构名称')),
                ('orgc_name', models.CharField(blank=True, help_text='丙方组织机构名称', max_length=256, null=True, verbose_name='丙方组织机构名称')),
                ('sign_time', models.DateField(blank=True, help_text='签订时间', null=True, verbose_name='签订时间')),
                ('sign_addr', models.CharField(blank=True, help_text='签订地点', max_length=256, null=True, verbose_name='签订地点')),
                ('name', models.CharField(help_text='服务名称', max_length=256, verbose_name='服务名称')),
                ('sn', models.CharField(blank=True, help_text='服务编号', max_length=256, null=True, verbose_name='服务编号')),
                ('price', models.DecimalField(blank=True, decimal_places=4, help_text='服务价格', max_digits=16, null=True, verbose_name='服务价格')),
                ('desc', models.TextField(blank=True, help_text='服务内容', null=True, verbose_name='服务内容')),
                ('deadline', models.CharField(blank=True, help_text='服务期限', max_length=32, null=True, verbose_name='服务期限')),
                ('start_time', models.DateField(blank=True, help_text='服务开始时间', null=True, verbose_name='服务开始时间')),
                ('end_time', models.DateField(blank=True, help_text='服务结束时间', null=True, verbose_name='服务结束时间')),
                ('file', models.TextField(blank=True, help_text='附件', null=True, verbose_name='附件')),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('field_01', models.CharField(blank=True, db_index=True, help_text='idx', max_length=1023, null=True, verbose_name='Field 01')),
                ('field_02', models.CharField(blank=True, db_index=True, help_text='idx', max_length=1023, null=True, verbose_name='Field 02')),
                ('field_03', models.CharField(blank=True, db_index=True, help_text='idx', max_length=1023, null=True, verbose_name='Field 03')),
                ('field_04', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 04')),
                ('field_05', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 05')),
                ('field_06', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 06')),
                ('field_07', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 07')),
                ('field_08', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 08')),
                ('field_09', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 09')),
                ('field_10', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 10')),
                ('text_01', models.TextField(blank=True, null=True, verbose_name='Text 01')),
                ('int_01', models.BigIntegerField(blank=True, db_index=True, help_text='idx', null=True, verbose_name='Int 01')),
                ('int_02', models.BigIntegerField(blank=True, db_index=True, help_text='idx', null=True, verbose_name='Int 02')),
                ('int_03', models.BigIntegerField(blank=True, null=True, verbose_name='Int 03')),
                ('int_04', models.BigIntegerField(blank=True, null=True, verbose_name='Int 04')),
                ('int_05', models.BigIntegerField(blank=True, null=True, verbose_name='Int 05')),
                ('int_06', models.BigIntegerField(blank=True, null=True, verbose_name='Int 06')),
                ('int_07', models.BigIntegerField(blank=True, null=True, verbose_name='Int 07')),
                ('int_08', models.BigIntegerField(blank=True, null=True, verbose_name='Int 08')),
                ('int_09', models.BigIntegerField(blank=True, null=True, verbose_name='Int 09')),
                ('int_10', models.BigIntegerField(blank=True, null=True, verbose_name='Int 10')),
                ('float_01', models.DecimalField(blank=True, db_index=True, decimal_places=4, help_text='idx', max_digits=16, null=True, verbose_name='Float 01')),
                ('float_02', models.DecimalField(blank=True, db_index=True, decimal_places=4, help_text='idx', max_digits=16, null=True, verbose_name='Float 02')),
                ('float_03', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Float 03')),
                ('float_04', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Float 04')),
                ('float_05', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Float 05')),
                ('float_06', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Float 06')),
                ('float_07', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Float 07')),
                ('float_08', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Float 08')),
                ('float_09', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Float 09')),
                ('float_10', models.DecimalField(blank=True, decimal_places=4, max_digits=16, null=True, verbose_name='Float 10')),
                ('article', models.ForeignKey(blank=True, db_constraint=False, help_text='介绍 article_id to article_article', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='article.article', verbose_name='内容链接')),
                ('create_user', models.ForeignKey(blank=True, db_constraint=False, help_text='创建人 create_user_id to usercenter_user', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建人')),
                ('customera_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer.customer', verbose_name='甲方ID customera_id_id to customer_customer')),
                ('customerb_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer.customer', verbose_name='乙方ID customerb_id_id to customer_customer')),
                ('customerc_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer.customer', verbose_name='丙方ID customerc_id_id to customer_customer')),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='usercenter.department')),
                ('orga_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.org', verbose_name='甲方组织机构ID orga_id_id to org_org')),
                ('orgb_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.org', verbose_name='乙方组织机构ID orgb_id_id to org_org')),
                ('orgc_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.org', verbose_name='丙方组织机构ID orgc_id_id to org_org')),
                ('template', models.ForeignKey(blank=True, db_constraint=False, help_text='template_id to formtemplate_formtemplate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='formtemplate.formtemplate', verbose_name='模版')),
                ('usera_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='甲方ID usera_id_id to usercenter_user')),
                ('userb_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='乙方ID userb_id_id to usercenter_user')),
                ('userc_id', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='丙方ID userc_id_id to usercenter_user')),
            ],
            options={
                'verbose_name': '服务',
                'verbose_name_plural': '服务',
            },
        ),
    ]
