# Generated by Django 3.2.10 on 2021-12-31 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        ('customer', '0002_auto_20211231_1053'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='services',
            name='customera_id',
        ),
        migrations.RemoveField(
            model_name='services',
            name='customerb_id',
        ),
        migrations.RemoveField(
            model_name='services',
            name='customerc_id',
        ),
        migrations.RemoveField(
            model_name='services',
            name='orga_id',
        ),
        migrations.RemoveField(
            model_name='services',
            name='orgb_id',
        ),
        migrations.RemoveField(
            model_name='services',
            name='orgc_id',
        ),
        migrations.RemoveField(
            model_name='services',
            name='usera_id',
        ),
        migrations.RemoveField(
            model_name='services',
            name='userb_id',
        ),
        migrations.RemoveField(
            model_name='services',
            name='userc_id',
        ),
        migrations.AddField(
            model_name='services',
            name='customera',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer.customer', verbose_name='甲方ID customera_id to customer_customer'),
        ),
        migrations.AddField(
            model_name='services',
            name='customerb',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer.customer', verbose_name='乙方ID customerb_id to customer_customer'),
        ),
        migrations.AddField(
            model_name='services',
            name='customerc',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer.customer', verbose_name='丙方ID customerc_id to customer_customer'),
        ),
        migrations.AddField(
            model_name='services',
            name='orga',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.org', verbose_name='甲方组织机构ID orga_id to org_org'),
        ),
        migrations.AddField(
            model_name='services',
            name='orgb',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.org', verbose_name='乙方组织机构ID orgb_id to org_org'),
        ),
        migrations.AddField(
            model_name='services',
            name='orgc',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='org.org', verbose_name='丙方组织机构ID orgc_id to org_org'),
        ),
        migrations.AddField(
            model_name='services',
            name='usera',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='甲方ID usera_id to usercenter_user'),
        ),
        migrations.AddField(
            model_name='services',
            name='userb',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='乙方ID userb_id to usercenter_user'),
        ),
        migrations.AddField(
            model_name='services',
            name='userc',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='丙方ID userc_id to usercenter_user'),
        ),
    ]
