# Generated by Django 3.2.10 on 2022-01-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20211231_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='obj_id',
            field=models.CharField(blank=True, help_text='保存人表、物表、服务表、机构表数据ID', max_length=32, null=True, verbose_name='外键字段'),
        ),
    ]
