# Generated by Django 3.2.11 on 2022-02-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_auto_20220120_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='a_persion',
            field=models.CharField(blank=True, help_text='甲方联系人', max_length=32, null=True, verbose_name='甲方联系人'),
        ),
        migrations.AddField(
            model_name='services',
            name='a_phone',
            field=models.CharField(blank=True, help_text='甲方联系电话', max_length=32, null=True, verbose_name='甲方联系电话'),
        ),
        migrations.AddField(
            model_name='services',
            name='audit1_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='报审金额', max_digits=16, null=True, verbose_name='报审金额'),
        ),
        migrations.AddField(
            model_name='services',
            name='audit2_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='初审金额', max_digits=16, null=True, verbose_name='初审金额'),
        ),
        migrations.AddField(
            model_name='services',
            name='audit3_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='终审金额', max_digits=16, null=True, verbose_name='终审金额'),
        ),
        migrations.AddField(
            model_name='services',
            name='audit_status',
            field=models.CharField(blank=True, help_text='审计或验收阶段状态', max_length=64, null=True, verbose_name='审计或验收阶段状态'),
        ),
        migrations.AddField(
            model_name='services',
            name='audit_time',
            field=models.DateTimeField(blank=True, help_text='审计时间', null=True, verbose_name='审计时间'),
        ),
        migrations.AddField(
            model_name='services',
            name='b_persion',
            field=models.CharField(blank=True, help_text='乙方联系人', max_length=32, null=True, verbose_name='乙方联系人'),
        ),
        migrations.AddField(
            model_name='services',
            name='b_phone',
            field=models.CharField(blank=True, help_text='乙方联系电话', max_length=32, null=True, verbose_name='乙方联系电话'),
        ),
        migrations.AddField(
            model_name='services',
            name='bidding_company',
            field=models.CharField(blank=True, help_text='招标单位名称或ID', max_length=256, null=True, verbose_name='招标单位'),
        ),
        migrations.AddField(
            model_name='services',
            name='bidding_time',
            field=models.DateTimeField(blank=True, help_text='招标时间', null=True, verbose_name='招标时间'),
        ),
        migrations.AddField(
            model_name='services',
            name='c_persion',
            field=models.CharField(blank=True, help_text='丙方联系人', max_length=32, null=True, verbose_name='丙方联系人'),
        ),
        migrations.AddField(
            model_name='services',
            name='c_phone',
            field=models.CharField(blank=True, help_text='丙方联系电话', max_length=32, null=True, verbose_name='丙方联系电话'),
        ),
        migrations.AddField(
            model_name='services',
            name='check_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='验收金额', max_digits=16, null=True, verbose_name='验收金额'),
        ),
        migrations.AddField(
            model_name='services',
            name='check_time',
            field=models.DateTimeField(blank=True, help_text='验收时间', null=True, verbose_name='验收时间'),
        ),
        migrations.AddField(
            model_name='services',
            name='construction_status',
            field=models.CharField(blank=True, help_text='施工阶段状态', max_length=64, null=True, verbose_name='施工阶段状态'),
        ),
        migrations.AddField(
            model_name='services',
            name='contract_price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='合同价格', max_digits=16, null=True, verbose_name='合同价格'),
        ),
        migrations.AddField(
            model_name='services',
            name='contract_sn',
            field=models.CharField(blank=True, db_index=True, help_text='合同编号', max_length=256, null=True, verbose_name='合同编号'),
        ),
        migrations.AddField(
            model_name='services',
            name='datetime_01',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datetime 01'),
        ),
        migrations.AddField(
            model_name='services',
            name='datetime_02',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datetime 02'),
        ),
        migrations.AddField(
            model_name='services',
            name='datetime_03',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datetime 03'),
        ),
        migrations.AddField(
            model_name='services',
            name='datetime_04',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datetime 04'),
        ),
        migrations.AddField(
            model_name='services',
            name='datetime_05',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Datetime 05'),
        ),
        migrations.AddField(
            model_name='services',
            name='design_status',
            field=models.CharField(blank=True, help_text='设计阶段状态', max_length=64, null=True, verbose_name='设计阶段状态'),
        ),
        migrations.AlterField(
            model_name='services',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='限定价格', max_digits=16, null=True, verbose_name='限定价格'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sn',
            field=models.CharField(blank=True, db_index=True, help_text='服务编号', max_length=256, null=True, verbose_name='服务编号'),
        ),
    ]
