# Generated by Django 3.2.11 on 2022-02-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_auto_20220218_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='date_01',
            field=models.DateField(blank=True, null=True, verbose_name='Date 01'),
        ),
        migrations.AddField(
            model_name='services',
            name='date_02',
            field=models.DateField(blank=True, null=True, verbose_name='Date 02'),
        ),
        migrations.AddField(
            model_name='services',
            name='date_03',
            field=models.DateField(blank=True, null=True, verbose_name='Date 03'),
        ),
        migrations.AddField(
            model_name='services',
            name='date_04',
            field=models.DateField(blank=True, null=True, verbose_name='Date 04'),
        ),
        migrations.AddField(
            model_name='services',
            name='date_05',
            field=models.DateField(blank=True, null=True, verbose_name='Date 05'),
        ),
    ]
