# Generated by Django 3.2.11 on 2022-03-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_auto_20220223_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='end_time',
            field=models.DateField(blank=True, help_text='服务结束日期', null=True, verbose_name='服务结束日期'),
        ),
        migrations.AlterField(
            model_name='services',
            name='start_time',
            field=models.DateField(blank=True, help_text='服务开始日期', null=True, verbose_name='服务开始日期'),
        ),
    ]
