# Generated by Django 3.2.11 on 2022-07-14 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_auto_20220331_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='a_persion',
            field=models.CharField(blank=True, help_text='甲方联系人', max_length=512, null=True, verbose_name='甲方联系人'),
        ),
        migrations.AlterField(
            model_name='services',
            name='a_phone',
            field=models.CharField(blank=True, help_text='甲方联系电话', max_length=512, null=True, verbose_name='甲方联系电话'),
        ),
        migrations.AlterField(
            model_name='services',
            name='b_persion',
            field=models.CharField(blank=True, help_text='乙方联系人', max_length=512, null=True, verbose_name='乙方联系人'),
        ),
        migrations.AlterField(
            model_name='services',
            name='b_phone',
            field=models.CharField(blank=True, help_text='乙方联系电话', max_length=512, null=True, verbose_name='乙方联系电话'),
        ),
        migrations.AlterField(
            model_name='services',
            name='c_persion',
            field=models.CharField(blank=True, help_text='丙方联系人', max_length=512, null=True, verbose_name='丙方联系人'),
        ),
        migrations.AlterField(
            model_name='services',
            name='c_phone',
            field=models.CharField(blank=True, help_text='丙方联系电话', max_length=512, null=True, verbose_name='丙方联系电话'),
        ),
    ]
