# Generated by Django 4.2.8 on 2024-08-30 11:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('service', '0012_auto_20220714_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='用户ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='usercenter_user.id'),
        ),
    ]
