# Generated by Django 3.2.10 on 2021-12-29 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utility.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailBox',
            fields=[
                ('id', utility.db_fields.TableNamePKField(blank=True, default=None, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('mailbox', 'mailbox'), ('notice', 'notice')], default='notice', help_text='消息类型', max_length=8, verbose_name='消息类型')),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('org_id', models.IntegerField(db_index=True, default=1, verbose_name='组织ID')),
                ('biz_id', models.IntegerField(db_index=True, default=1, verbose_name='业务ID')),
                ('src_id', models.IntegerField(db_index=True, default=1, verbose_name='数据源ID')),
                ('obj_id', models.CharField(blank=True, help_text='关联对象ID', max_length=64, null=True, verbose_name='关联对象ID')),
                ('title', models.CharField(blank=True, help_text='标题', max_length=255, null=True, verbose_name='标题')),
                ('content', models.TextField(blank=True, help_text='内容', null=True, verbose_name='内容')),
                ('is_published', models.BooleanField(default=True, help_text='已发布', verbose_name='已发布')),
                ('publish_date', models.DateField(blank=True, help_text='发布日期', null=True, verbose_name='发布日期')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('last_modify', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='最后修改时间')),
                ('is_read', models.BooleanField(default=False, help_text='已读', verbose_name='已读')),
                ('is_public', models.BooleanField(default=True, help_text='全局公开[false为部分公开，须填写public_user]', verbose_name='全局公开')),
                ('from_user', models.ForeignKey(blank=True, db_constraint=False, help_text='发送用户ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='发送用户')),
                ('public_user', models.ManyToManyField(blank=True, help_text='公开范围', related_name='own_notices', to=settings.AUTH_USER_MODEL, verbose_name='公开范围')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='接收用户ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='接收用户')),
            ],
            options={
                'verbose_name': '01.通知',
                'verbose_name_plural': '01.通知',
                'ordering': ('-create_time', 'user_id'),
            },
        ),
    ]
