# Generated by Django 3.2.10 on 2021-12-31 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baseconfig', '0001_initial'),
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='msg_type',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='消息分类', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='baseconfig.basetree'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='obj_type',
            field=models.CharField(blank=True, help_text='关联对象类型', max_length=64, null=True, verbose_name='关联对象类型'),
        ),
    ]
