# Generated by Django 3.2.11 on 2022-02-15 14:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notice', '0004_alter_mailbox_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='public_user',
            field=models.ManyToManyField(blank=True, db_constraint=False, help_text='公开范围', related_name='own_notices', to=settings.AUTH_USER_MODEL, verbose_name='公开范围'),
        ),
    ]
