# Generated by Django 3.2.11 on 2022-02-15 14:59

from django.db import migrations
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0005_auto_20220215_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailbox',
            name='id',
            field=utility.db_fields.TableNamePKField('mb', serialize=False),
        ),
    ]
