# Generated by Django 3.2.11 on 2023-08-10 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0019_department_dep_manager'),
        ('notice', '0006_alter_mailbox_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='department_range',
            field=models.CharField(blank=True, choices=[('本级', '本级'), ('本级及以下', '本级及以下')], help_text='部门范围', max_length=32, null=True, verbose_name='部门公布范围'),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='departments',
            field=models.ManyToManyField(blank=True, db_constraint=False, help_text='部门范围', related_name='notices', to='usercenter.Department', verbose_name='部门范围'),
        ),
    ]
