# Generated by Django 4.2.16 on 2025-02-10 11:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0023_funcpermission_creator_alter_funcpermission_codename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('baseconfig', '0011_baseconfigfileupload_is_deleted'),
        ('notice', '0007_auto_20230810_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticePool',
            fields=[
                ('id', utility.db_fields.TableNamePKField('np', editable=False, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('org_id', models.IntegerField(db_index=True, default=1, verbose_name='组织ID')),
                ('biz_id', models.IntegerField(db_index=True, default=1, verbose_name='业务ID')),
                ('src_id', models.IntegerField(db_index=True, default=1, verbose_name='数据源ID')),
                ('obj_id', models.CharField(blank=True, db_index=True, help_text='关联对象ID', max_length=64, null=True, verbose_name='关联对象ID')),
                ('obj_type', models.CharField(blank=True, db_index=True, help_text='关联对象类型', max_length=64, null=True, verbose_name='关联对象类型')),
                ('title', models.CharField(blank=True, help_text='标题', max_length=255, null=True, verbose_name='标题')),
                ('content', models.TextField(blank=True, help_text='内容', null=True, verbose_name='内容')),
                ('send_time', models.DateTimeField(blank=True, db_index=True, help_text='发送时间', null=True, verbose_name='发送时间')),
                ('is_circulation', models.BooleanField(default=False, help_text='循环发送', verbose_name='循环发送')),
                ('circulation_time', models.DurationField(blank=True, help_text='循环时间', null=True, verbose_name='循环时间')),
                ('is_sent', models.BooleanField(db_index=True, default=False, help_text='已发送', verbose_name='已发送')),
                ('from_user_display', models.CharField(blank=True, help_text='发送用户', max_length=64, null=True, verbose_name='发送用户')),
                ('is_public', models.BooleanField(default=False, help_text='全局公开[false为部分公开，须填写send_to]', verbose_name='全局公开')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('last_modify', models.DateTimeField(auto_now=True, help_text='最后修改时间', verbose_name='最后修改时间')),
                ('department_range', models.CharField(blank=True, choices=[('本级', '本级'), ('本级及以下', '本级及以下')], help_text='部门范围', max_length=32, null=True, verbose_name='部门公布范围')),
                ('channel', models.CharField(choices=[('email', 'email'), ('sms', '短信'), ('wxa', '微信小程序'), ('mailbox', '站内信')], default='mailbox', help_text='发送渠道', max_length=16, verbose_name='发送渠道')),
                ('departments', models.ManyToManyField(blank=True, db_constraint=False, help_text='部门范围', related_name='+', to='usercenter.department', verbose_name='部门范围')),
                ('from_user', models.ForeignKey(blank=True, db_constraint=False, help_text='发送用户ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='发送用户')),
                ('msg_type', models.ForeignKey(blank=True, db_constraint=False, help_text='消息分类', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='baseconfig.basetree')),
                ('send_to', models.ManyToManyField(blank=True, db_constraint=False, help_text='发送对象', related_name='notice_pool', to=settings.AUTH_USER_MODEL, verbose_name='发送对象')),
            ],
            options={
                'verbose_name': '02.通知池',
                'verbose_name_plural': '02.通知池',
            },
        ),
    ]
