# Generated by Django 4.2.16 on 2025-03-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0008_noticepool'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticepool',
            name='error_message',
            field=models.TextField(blank=True, help_text='错误信息', null=True, verbose_name='错误信息'),
        ),
    ]
