# Generated by Django 3.2.10 on 2022-01-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formtemplate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formfields',
            name='width',
        ),
        migrations.AddField(
            model_name='formfields',
            name='is_related',
            field=models.BooleanField(default=False, help_text='是否是外键字段(obj_id)关联显示内容'),
        ),
    ]
