# Generated by Django 3.2.11 on 2022-01-18 09:57

from django.db import migrations
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('formtemplate', '0002_auto_20220105_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdatareportconf',
            name='id',
            field=utility.db_fields.TableNamePKField(blank=True, default=utility.db_fields.TableNamePKField.auto_id, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formfields',
            name='id',
            field=utility.db_fields.TableNamePKField(blank=True, default=utility.db_fields.TableNamePKField.auto_id, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='id',
            field=utility.db_fields.TableNamePKField(blank=True, default=utility.db_fields.TableNamePKField.auto_id, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
