# Generated by Django 3.2.11 on 2022-01-20 11:04

from django.db import migrations
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('formtemplate', '0004_auto_20220119_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdatareportconf',
            name='id',
            field=utility.db_fields.TableNamePKField(blank=True, default=utility.db_fields.TableNamePKField.auto_id, editable=False, max_length=32, prefix='report', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formfields',
            name='id',
            field=utility.db_fields.TableNamePKField(blank=True, default=utility.db_fields.TableNamePKField.auto_id, editable=False, max_length=32, prefix='FF', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='formtemplate',
            name='id',
            field=utility.db_fields.TableNamePKField(blank=True, default=utility.db_fields.TableNamePKField.auto_id, editable=False, max_length=32, prefix='FT', primary_key=True, serialize=False),
        ),
    ]
