# Generated by Django 3.2.11 on 2022-02-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formtemplate', '0005_auto_20220120_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfields',
            name='desc',
            field=models.CharField(blank=True, help_text='字段说明', max_length=255, null=True, verbose_name='字段说明'),
        ),
    ]
