# Generated by Django 3.2.11 on 2022-03-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formtemplate', '0006_formfields_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='header_conf',
            field=models.TextField(blank=True, help_text='导入导出表头定义(用JSON字符串存储)', null=True, verbose_name='导入导出表头定义'),
        ),
    ]
