# Generated by Django 3.2.11 on 2022-05-07 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0012_alter_funcgroup_name'),
        ('formtemplate', '0007_formtemplate_header_conf'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='department',
            field=models.ManyToManyField(blank=True, help_text='部门ID数组', related_name='_formtemplate_formtemplate_department_+', to='usercenter.Department', verbose_name='usercenter_department.id'),
        ),
    ]
