# Generated by Django 3.2.11 on 2022-12-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formtemplate', '0008_formtemplate_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfields',
            name='is_required',
            field=models.BooleanField(blank=True, default=True, help_text='必填项', null=True, verbose_name='必填项'),
        ),
    ]
