# Generated by Django 3.2.10 on 2023-03-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formtemplate', '0009_alter_formfields_is_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfields',
            name='is_vant_show',
            field=models.BooleanField(default=False, help_text='手机端查看项', verbose_name='手机端查看项'),
        ),
    ]
