# Generated by Django 3.2.11 on 2023-08-29 15:04

import os
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formtemplate', '0010_formfields_is_vant_show'),
    ]

    operations = [
        migrations.RunSQL(
            sql=open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'update_formdata_001.sql'), 'r', encoding='UTF8').read()
        ),
    ]
