# Generated by Django 4.2.8 on 2024-06-25 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0021_user_password_date'),
        ('formtemplate', '0011_auto_20230829_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='from_template',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='复制自模板', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='formtemplate.formtemplate'),
        ),
    ]
