# Generated by Django 4.2.8 on 2024-06-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0021_user_password_date'),
        ('formtemplate', '0012_formtemplate_from_template_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfields',
            name='unique',
            field=models.BooleanField(default=False, help_text='和org_id联合唯一', verbose_name='和org_id联合唯一'),
        ),
    ]
