# Generated by Django 4.2.8 on 2024-07-11 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0021_user_password_date'),
        ('formtemplate', '0013_formfields_unique_alter_formtemplate_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='from_template',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='复制自模板', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='formtemplate.formtemplate'),
        ),
    ]
