# Generated by Django 4.2.8 on 2024-08-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formtemplate', '0015_manytomanydata_formfields_is_m2m_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfields',
            name='m2m_model',
            field=models.CharField(blank=True, choices=[('org', 'org'), ('customer', 'customer'), ('goods', 'goods'), ('service', 'service'), ('formdata', 'formdata'), ('basetree', 'basetree'), ('user', 'user'), ('department', 'department'), ('parameters', 'parameters'), ('article', 'article'), ('account', 'account')], help_text='多对多关联模型', max_length=255, null=True, verbose_name='多对多关联模型'),
        ),
    ]
