# Generated by Django 4.2.8 on 2024-08-30 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formtemplate', '0016_formfields_m2m_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='manytomanydata',
            name='m_from_field',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='formtemplate.formfields'),
        ),
    ]
