# Generated by Django 4.2.8 on 2024-09-18 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercenter', '0023_funcpermission_creator_alter_funcpermission_codename'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formtemplate', '0017_manytomanydata_m_from_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdatareportconf',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formdatareportconf',
            name='permission',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='功能模块', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usercenter.funcpermission'),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='permission',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='功能模块', null=True, on_delete=django.db.models.deletion.SET_NULL, to='usercenter.funcpermission'),
        ),
    ]
