# Generated by Django 4.2.8 on 2024-09-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formtemplate', '0018_formdatareportconf_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='need_login',
            field=models.BooleanField(default=False, help_text='需登陆', verbose_name='需登陆'),
        ),
    ]
