# Generated by Django 4.2.8 on 2024-09-29 16:56

from django.db import migrations, models
import django.db.models.deletion
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('formtemplate', '0019_alter_formtemplate_need_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormAggrgateFields',
            fields=[
                ('id', utility.db_fields.TableNamePKField('FA', editable=False, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('org_id', models.IntegerField(db_index=True, default=1, verbose_name='组织ID')),
                ('src_id', models.IntegerField(db_index=True, default=0, verbose_name='分区ID')),
                ('biz_id', models.IntegerField(db_index=True, default=1, verbose_name='业务ID')),
                ('aggr_type', models.CharField(blank=True, choices=[('count', '去重计数'), ('sum', '求和'), ('avg', '平均值'), ('max', '最大值'), ('min', '最小值')], help_text='聚合类型', max_length=128, null=True, verbose_name='聚合类型')),
                ('aggr_name', models.CharField(blank=True, help_text='聚合名称', max_length=128, null=True, verbose_name='聚合名称')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=1023, null=True, verbose_name='描述')),
                ('field', models.ForeignKey(db_constraint=False, help_text='字段ID', on_delete=django.db.models.deletion.CASCADE, related_name='+', to='formtemplate.formfields')),
                ('template', models.ForeignKey(db_constraint=False, help_text='模板ID', on_delete=django.db.models.deletion.CASCADE, related_name='aggregate_fields', to='formtemplate.formtemplate')),
            ],
            options={
                'verbose_name': '02.模板聚合字段',
                'verbose_name_plural': '02.模板聚合字段',
            },
        ),
    ]
