# Generated by Django 4.2.16 on 2025-02-26 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('formtemplate', '0020_formaggrgatefields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formdatareportconf',
            name='creator',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='创建人', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
