# Generated by Django 3.2.10 on 2021-12-29 15:44

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(help_text='参数分类名称', max_length=16, verbose_name='参数分类')),
                ('name', models.CharField(max_length=30)),
                ('value', models.CharField(blank=True, max_length=64, null=True)),
                ('field_01', models.CharField(blank=True, max_length=64, null=True)),
                ('field_02', models.CharField(blank=True, max_length=64, null=True)),
                ('field_03', models.CharField(blank=True, max_length=64, null=True)),
                ('remark', models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注')),
                ('field_json', models.TextField(blank=True, help_text='JSON字段', null=True, verbose_name='JSON字段')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, help_text='上级', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='parameter.parameters', verbose_name='上级')),
            ],
            options={
                'verbose_name': '常用参数表',
                'verbose_name_plural': '常用参数表',
            },
        ),
    ]
