# Generated by Django 3.2.11 on 2022-01-18 10:01

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utility.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', utility.db_fields.TableNamePKField(blank=True, default=utility.db_fields.TableNamePKField.auto_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('org_id', models.IntegerField(db_index=True, default=1, verbose_name='组织ID')),
                ('biz_id', models.IntegerField(db_index=True, default=1, verbose_name='业务ID')),
                ('src_id', models.IntegerField(db_index=True, default=1, verbose_name='数据源ID')),
                ('obj_id', models.CharField(blank=True, db_index=True, help_text='所属对象ID', max_length=64, null=True, verbose_name='所属对象ID')),
                ('acc_1_name', models.CharField(blank=True, help_text='账户1名称', max_length=64, null=True, verbose_name='账户1名称')),
                ('acc_1_type', models.CharField(blank=True, help_text='账户1类型', max_length=64, null=True, verbose_name='账户1类型')),
                ('acc_1_balance', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), help_text='账户1余额', max_digits=14, null=True, verbose_name='账户1余额')),
                ('acc_1_lock', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), help_text='账户1锁定', max_digits=14, null=True, verbose_name='账户1锁定')),
                ('acc_2_name', models.CharField(blank=True, help_text='账户2名称', max_length=64, null=True, verbose_name='账户2名称')),
                ('acc_2_type', models.CharField(blank=True, help_text='账户2类型', max_length=64, null=True, verbose_name='账户2类型')),
                ('acc_2_balance', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), help_text='账户2余额', max_digits=14, null=True, verbose_name='账户2余额')),
                ('acc_2_lock', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), help_text='账户2锁定', max_digits=14, null=True, verbose_name='账户2锁定')),
                ('acc_3_name', models.CharField(blank=True, help_text='账户3名称', max_length=64, null=True, verbose_name='账户3名称')),
                ('acc_3_type', models.CharField(blank=True, help_text='账户3类型', max_length=64, null=True, verbose_name='账户3类型')),
                ('acc_3_balance', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), help_text='账户3余额', max_digits=14, null=True, verbose_name='账户3余额')),
                ('acc_3_lock', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), help_text='账户3锁定', max_digits=14, null=True, verbose_name='账户3锁定')),
                ('jifen_acc', models.CharField(blank=True, help_text='积分账户名称', max_length=64, null=True, verbose_name='积分账户名称')),
                ('jifen_balance', models.DecimalField(blank=True, decimal_places=3, default=Decimal('0'), help_text='积分余额', max_digits=14, null=True, verbose_name='积分余额')),
                ('create_time', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='用户ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '账户表',
                'verbose_name_plural': '账户表',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='AccountStatements',
            fields=[
                ('id', utility.db_fields.TableNamePKField(blank=True, default=utility.db_fields.TableNamePKField.auto_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('org_id', models.IntegerField(db_index=True, default=1, verbose_name='组织ID')),
                ('biz_id', models.IntegerField(db_index=True, default=1, verbose_name='业务ID')),
                ('src_id', models.IntegerField(db_index=True, default=1, verbose_name='数据源ID')),
                ('acc_name', models.CharField(blank=True, help_text='账户N名称', max_length=64, null=True, verbose_name='账户N名称')),
                ('record_type', models.CharField(max_length=16, verbose_name='记录类型')),
                ('amount', models.DecimalField(decimal_places=3, help_text='金额', max_digits=14, verbose_name='金额')),
                ('used_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='已用金额', max_digits=14, verbose_name='已用金额')),
                ('end_time', models.DateTimeField(blank=True, help_text='到期时间', null=True, verbose_name='到期时间')),
                ('tpp_name', models.CharField(blank=True, help_text='第三方支付名称', max_length=16, null=True, verbose_name='第三方支付名称')),
                ('tpp_no', models.CharField(blank=True, help_text='第三方支付流水号', max_length=64, null=True, verbose_name='第三方支付流水号')),
                ('tpp_desc', models.TextField(blank=True, help_text='第三方支付其他信息', null=True, verbose_name='第三方支付其他信息')),
                ('desc', models.TextField(blank=True, help_text='说明', null=True, verbose_name='说明')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='更新时间')),
                ('acc', models.ForeignKey(db_constraint=False, help_text='账户ID', on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='account.account')),
            ],
            options={
                'verbose_name': '账户明细表',
                'verbose_name_plural': '账户明细表',
                'ordering': ['-id'],
            },
        ),
    ]
