# Generated by Django 3.2.11 on 2022-02-15 14:59

from django.db import migrations
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20220119_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=utility.db_fields.TableNamePKField('ACC', serialize=False),
        ),
        migrations.AlterField(
            model_name='accountstatements',
            name='id',
            field=utility.db_fields.TableNamePKField('ACCS', serialize=False),
        ),
    ]
