# Generated by Django 4.2.8 on 2024-09-23 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20220215_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatements',
            name='field_01',
            field=models.CharField(blank=True, help_text='备用字段01', max_length=64, null=True, verbose_name='备用字段01'),
        ),
        migrations.AddField(
            model_name='accountstatements',
            name='field_02',
            field=models.CharField(blank=True, help_text='备用字段02', max_length=64, null=True, verbose_name='备用字段02'),
        ),
        migrations.AddField(
            model_name='accountstatements',
            name='field_03',
            field=models.CharField(blank=True, help_text='备用字段03', max_length=64, null=True, verbose_name='备用字段03'),
        ),
        migrations.AddField(
            model_name='accountstatements',
            name='field_04',
            field=models.CharField(blank=True, help_text='备用字段04', max_length=64, null=True, verbose_name='备用字段04'),
        ),
        migrations.AddField(
            model_name='accountstatements',
            name='field_05',
            field=models.CharField(blank=True, help_text='备用字段05', max_length=64, null=True, verbose_name='备用字段05'),
        ),
        migrations.AddField(
            model_name='accountstatements',
            name='float_01',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='备用浮点01', max_digits=14, null=True, verbose_name='备用浮点01'),
        ),
        migrations.AddField(
            model_name='accountstatements',
            name='float_02',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='备用浮点02', max_digits=14, null=True, verbose_name='备用浮点02'),
        ),
        migrations.AddField(
            model_name='accountstatements',
            name='float_03',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='备用浮点03', max_digits=14, null=True, verbose_name='备用浮点03'),
        ),
        migrations.AddField(
            model_name='accountstatements',
            name='float_04',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='备用浮点04', max_digits=14, null=True, verbose_name='备用浮点04'),
        ),
        migrations.AddField(
            model_name='accountstatements',
            name='float_05',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='备用浮点05', max_digits=14, null=True, verbose_name='备用浮点05'),
        ),
    ]
