# Generated by Django 4.2.8 on 2024-09-26 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_accountstatements_field_01_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountstatements',
            name='order_num',
            field=models.CharField(blank=True, help_text='订单号', max_length=64, null=True, verbose_name='订单号'),
        ),
    ]
