# Generated by Django 3.2.10 on 2021-12-31 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org',
            name='mch_api_key',
        ),
        migrations.RemoveField(
            model_name='org',
            name='mch_cert',
        ),
        migrations.RemoveField(
            model_name='org',
            name='mch_id',
        ),
        migrations.RemoveField(
            model_name='org',
            name='mch_key',
        ),
        migrations.RemoveField(
            model_name='org',
            name='mch_sub_id',
        ),
        migrations.RemoveField(
            model_name='org',
            name='mp_aid',
        ),
        migrations.RemoveField(
            model_name='org',
            name='mp_name',
        ),
        migrations.RemoveField(
            model_name='org',
            name='mp_sk',
        ),
        migrations.RemoveField(
            model_name='org',
            name='wxa_aid',
        ),
        migrations.RemoveField(
            model_name='org',
            name='wxa_name',
        ),
        migrations.RemoveField(
            model_name='org',
            name='wxa_sk',
        ),
    ]
