# Generated by Django 3.2.11 on 2022-02-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0008_auto_20220120_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='org_id',
            field=models.IntegerField(db_index=True, default=1, verbose_name='组织ID'),
        ),
    ]
