# Generated by Django 3.2.11 on 2022-03-31 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0009_alter_org_org_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='registration_date',
            field=models.DateField(blank=True, help_text='登记日期', null=True, verbose_name='登记日期'),
        ),
    ]
