# Generated by Django 3.2.11 on 2023-11-14 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0010_alter_org_registration_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='field_11',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 11'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_12',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 12'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_13',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 13'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_14',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 14'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_15',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 15'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_16',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 16'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_17',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 17'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_18',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 18'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_19',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 19'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_20',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 20'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_21',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 21'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_22',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 22'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_23',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 23'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_24',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 24'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_25',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 25'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_26',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 26'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_27',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 27'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_28',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 28'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_29',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 29'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_30',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 30'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_31',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 31'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_32',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 32'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_33',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 33'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_34',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 34'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_35',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 35'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_36',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 36'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_37',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 37'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_38',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 38'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_39',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 39'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_40',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 40'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_41',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 41'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_42',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 42'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_43',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 43'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_44',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 44'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_45',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 45'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_46',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 46'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_47',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 47'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_48',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 48'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_49',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 49'),
        ),
        migrations.AddField(
            model_name='org',
            name='field_50',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 50'),
        ),
    ]
