# Generated by Django 4.2.8 on 2024-06-21 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0011_auto_20231114_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='gps_sn',
            field=models.CharField(blank=True, help_text='定位设备编号', max_length=256, null=True, verbose_name='定位设备编号'),
        ),
    ]
