# Generated by Django 3.2.10 on 2021-12-29 15:44

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utility.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usercenter', '0001_initial'),
        ('formtemplate', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', utility.db_fields.TableNamePKField(blank=True, default=None, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('org_id', models.IntegerField(db_index=True, default=1, verbose_name='组织ID')),
                ('biz_id', models.IntegerField(db_index=True, default=1, verbose_name='业务ID')),
                ('src_id', models.IntegerField(db_index=True, default=1, verbose_name='数据源ID')),
                ('sn', models.CharField(blank=True, db_index=True, help_text='编号', max_length=256, null=True, verbose_name='编号')),
                ('gps_sn', models.CharField(blank=True, help_text='定位设备编号', max_length=256, null=True, verbose_name='定位设备编号')),
                ('name', models.CharField(help_text='姓名', max_length=32, verbose_name='姓名')),
                ('en_name', models.CharField(blank=True, help_text='英文名', max_length=64, null=True, verbose_name='英文名')),
                ('old_name', models.CharField(blank=True, help_text='曾用名', max_length=64, null=True, verbose_name='曾用名')),
                ('nick_name', models.CharField(blank=True, help_text='昵称', max_length=31, null=True, verbose_name='昵称')),
                ('gender', models.CharField(choices=[('女', '女'), ('男', '男'), ('其它', '其它')], default='女', help_text='性别', max_length=2, verbose_name='性别')),
                ('country', models.CharField(blank=True, help_text='国籍', max_length=64, null=True, verbose_name='国籍')),
                ('nation', models.CharField(blank=True, help_text='民族', max_length=64, null=True, verbose_name='民族')),
                ('political_status', models.CharField(blank=True, help_text='政治面貌', max_length=64, null=True, verbose_name='政治面貌')),
                ('certificate_type', models.CharField(blank=True, help_text='证件类型', max_length=64, null=True, verbose_name='证件类型')),
                ('certificate_number', models.CharField(blank=True, help_text='证件号码', max_length=64, null=True, verbose_name='证件号码')),
                ('birthday', models.DateField(blank=True, help_text='出生日期', null=True, verbose_name='出生日期')),
                ('death_date', models.DateField(blank=True, help_text='死亡日期', null=True, verbose_name='死亡日期')),
                ('birthplace', models.CharField(blank=True, help_text='出生地', max_length=256, null=True, verbose_name='出生地')),
                ('hometown', models.CharField(blank=True, help_text='籍贯', max_length=256, null=True, verbose_name='籍贯')),
                ('address', models.TextField(blank=True, help_text='住址', null=True, verbose_name='住址')),
                ('mail', models.CharField(blank=True, help_text='邮箱', max_length=255, null=True, verbose_name='邮箱')),
                ('qq', models.CharField(blank=True, help_text='QQ', max_length=32, null=True, verbose_name='QQ')),
                ('phone_01', models.CharField(blank=True, help_text='联系电话1', max_length=32, null=True, verbose_name='联系电话1')),
                ('phone_02', models.CharField(blank=True, help_text='联系电话2', max_length=32, null=True, verbose_name='联系电话2')),
                ('emergency_contact', models.CharField(blank=True, help_text='紧急联系人', max_length=32, null=True, verbose_name='紧急联系人')),
                ('emergency_phone', models.CharField(blank=True, help_text='紧急联系电话', max_length=32, null=True, verbose_name='紧急联系电话')),
                ('issuing_authority', models.CharField(blank=True, help_text='发证机关', max_length=64, null=True, verbose_name='发证机关')),
                ('effective_start_date', models.DateField(blank=True, help_text='有效开始日期', null=True, verbose_name='有效开始日期')),
                ('effective_end_date', models.DateField(blank=True, help_text='有效结束日期', null=True, verbose_name='有效结束日期')),
                ('graduated_college', models.CharField(blank=True, help_text='毕业院校', max_length=256, null=True, verbose_name='毕业院校')),
                ('enrollment_date', models.DateField(blank=True, help_text='入学日期', null=True, verbose_name='入学日期')),
                ('graduation_date', models.DateField(blank=True, help_text='毕业日期', null=True, verbose_name='毕业日期')),
                ('education', models.CharField(blank=True, help_text='学历', max_length=256, null=True, verbose_name='学历')),
                ('academic_degree', models.CharField(blank=True, help_text='学位', max_length=256, null=True, verbose_name='学位')),
                ('majors', models.CharField(blank=True, help_text='专业', max_length=256, null=True, verbose_name='专业')),
                ('class_name', models.CharField(blank=True, help_text='班级', max_length=256, null=True, verbose_name='班级')),
                ('profession', models.CharField(blank=True, help_text='职业', max_length=256, null=True, verbose_name='职业')),
                ('qualification_name', models.CharField(blank=True, help_text='资格证书', max_length=256, null=True, verbose_name='资格证书')),
                ('qualification_number', models.CharField(blank=True, help_text='资格证书编号', max_length=256, null=True, verbose_name='资格证书编号')),
                ('qualification_level', models.CharField(blank=True, help_text='资格证书等级', max_length=256, null=True, verbose_name='资格证书等级')),
                ('qualification_source', models.CharField(blank=True, help_text='资格证书发证机构', max_length=256, null=True, verbose_name='资格证书发证机构')),
                ('work_place', models.CharField(blank=True, help_text='工作单位', max_length=255, null=True, verbose_name='工作单位')),
                ('inauguration_date', models.DateField(blank=True, help_text='入职时间', null=True, verbose_name='入职时间')),
                ('job_position', models.CharField(blank=True, help_text='职位', max_length=32, null=True, verbose_name='职位')),
                ('job_post', models.CharField(blank=True, help_text='岗位', max_length=32, null=True, verbose_name='岗位')),
                ('job_content', models.TextField(blank=True, help_text='工作内容', null=True, verbose_name='工作内容')),
                ('id_photo', models.TextField(blank=True, help_text='证件照片', null=True, verbose_name='证件照片')),
                ('photo', models.TextField(blank=True, help_text='本人照片', null=True, verbose_name='本人照片')),
                ('qrcode', models.TextField(blank=True, help_text='二维码', null=True, verbose_name='二维码')),
                ('marital_status', models.CharField(choices=[('已婚', '已婚'), ('未婚', '未婚'), ('未知', '未知')], default='未知', help_text='婚姻状况', max_length=2, verbose_name='婚姻状况')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('end_date', models.DateField(default=datetime.date(2099, 12, 31), help_text='有效期截止日', verbose_name='有效期截止日')),
                ('remark', models.TextField(blank=True, help_text='备注', null=True, verbose_name='备注')),
                ('field_01', models.CharField(blank=True, db_index=True, help_text='idx', max_length=1023, null=True, verbose_name='Field 01')),
                ('field_02', models.CharField(blank=True, db_index=True, help_text='idx', max_length=1023, null=True, verbose_name='Field 02')),
                ('field_03', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 03')),
                ('field_04', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 04')),
                ('field_05', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 05')),
                ('field_06', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 06')),
                ('field_07', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 07')),
                ('field_08', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 08')),
                ('field_09', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 09')),
                ('field_10', models.CharField(blank=True, max_length=1023, null=True, verbose_name='Field 10')),
                ('datetime_01', models.DateTimeField(blank=True, db_index=True, help_text='idx', null=True, verbose_name='DateTime 01')),
                ('datetime_02', models.DateTimeField(blank=True, db_index=True, help_text='idx', null=True, verbose_name='DateTime 02')),
                ('int_01', models.BigIntegerField(blank=True, db_index=True, help_text='idx', null=True, verbose_name='Int 01')),
                ('int_02', models.BigIntegerField(blank=True, db_index=True, help_text='idx', null=True, verbose_name='Int 02')),
                ('int_03', models.BigIntegerField(blank=True, null=True, verbose_name='Int 03')),
                ('int_04', models.BigIntegerField(blank=True, null=True, verbose_name='Int 04')),
                ('int_05', models.BigIntegerField(blank=True, null=True, verbose_name='Int 05')),
                ('text_01', models.TextField(blank=True, null=True, verbose_name='Text 01')),
                ('json_01', models.TextField(blank=True, null=True, verbose_name='JSON 01')),
                ('department', models.ForeignKey(blank=True, help_text='部门ID department_id to usercenter_department', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='usercenter.department', verbose_name='部门')),
                ('template', models.ForeignKey(blank=True, db_constraint=False, help_text='模版ID formtemplate_id to formtemplate_formtemplate', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='formtemplate.formtemplate', verbose_name='模版')),
                ('user', models.ForeignKey(blank=True, db_constraint=False, help_text='用户ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '01.人员',
                'verbose_name_plural': '01.人员',
            },
        ),
    ]
