# Generated by Django 3.2.10 on 2021-12-31 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, help_text='性别', max_length=2, null=True, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, help_text='姓名', max_length=32, null=True, verbose_name='姓名'),
        ),
    ]
