# Generated by Django 3.2.10 on 2022-01-06 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_obj_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='altitude',
            field=models.FloatField(blank=True, help_text='海拔 idx', null=True, verbose_name='海拔'),
        ),
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.FloatField(blank=True, help_text='纬度 idx', null=True, verbose_name='纬度'),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.FloatField(blank=True, help_text='经度 idx', null=True, verbose_name='经度'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='create_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
