# Generated by Django 3.2.11 on 2022-10-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20220120_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='end_date',
            field=models.DateField(blank=True, help_text='有效期截止日', null=True, verbose_name='有效期截止日'),
        ),
    ]
