# Generated by Django 3.2.10 on 2023-07-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_auto_20221019_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(blank=True, default='未知', help_text='婚姻状况', max_length=32, null=True, verbose_name='婚姻状况'),
        ),
    ]
