# Generated by Django 3.2.10 on 2021-12-31 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='department',
        ),
    ]
