# Generated by Django 3.2.11 on 2022-01-18 09:57

from django.db import migrations
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_article_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=utility.db_fields.TableNamePKField(blank=True, default=utility.db_fields.TableNamePKField.auto_id, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
    ]
