# Generated by Django 3.2.11 on 2022-02-15 14:59

from django.db import migrations
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_alter_article_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='id',
            field=utility.db_fields.TableNamePKField('art', serialize=False),
        ),
    ]
