# Generated by Django 3.2.10 on 2021-12-29 15:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import utility.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialDynamic',
            fields=[
                ('id', utility.db_fields.TableNamePKField(blank=True, default=None, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('org_id', models.IntegerField(db_index=True, default=1, verbose_name='组织ID')),
                ('biz_id', models.IntegerField(db_index=True, default=1, verbose_name='业务ID')),
                ('src_id', models.IntegerField(db_index=True, default=1, verbose_name='数据源ID')),
                ('publish_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('title', models.CharField(blank=True, max_length=128, null=True, verbose_name='标题')),
                ('content', models.TextField(blank=True, help_text='发布内容', null=True, verbose_name='发布内容')),
                ('visible', models.CharField(choices=[('所有人可见', '所有人可见'), ('仅自己可见', '仅自己可见'), ('好友可见', '好友可见')], help_text='可见性: 所有人可见, 仅自己可见, 好友可见', max_length=15, verbose_name='可见性')),
                ('is_anonymous', models.BooleanField(default=False, help_text='是否匿名发布: default false', verbose_name='是否匿名发布')),
                ('address', models.CharField(blank=True, help_text='所在位置', max_length=500, null=True, verbose_name='所在位置')),
                ('images', models.TextField(blank=True, help_text='用户动态图片JSON数组', null=True, verbose_name='用户动态图片')),
                ('is_hot', models.BooleanField(default=False, help_text='热门', verbose_name='热门')),
                ('is_pub', models.BooleanField(default=False, help_text='精选', verbose_name='精选')),
                ('is_deleted', models.BooleanField(default=False, help_text='被删除', verbose_name='被删除')),
                ('desc', models.TextField(blank=True, help_text='附加字段', null=True, verbose_name='附加字段')),
                ('user', models.ForeignKey(db_constraint=False, help_text='user_id to usercenter_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发布者')),
            ],
            options={
                'verbose_name': 'Social: 动态',
                'verbose_name_plural': 'Social: 动态',
                'ordering': ['-publish_time'],
            },
        ),
        migrations.CreateModel(
            name='SocialComment',
            fields=[
                ('id', utility.db_fields.TableNamePKField(blank=True, default=None, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('org_id', models.IntegerField(db_index=True, default=1, verbose_name='组织ID')),
                ('biz_id', models.IntegerField(db_index=True, default=1, verbose_name='业务ID')),
                ('src_id', models.IntegerField(db_index=True, default=1, verbose_name='数据源ID')),
                ('content', models.CharField(max_length=255, verbose_name='评论内容')),
                ('comment_time', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('thumbs_up', models.PositiveIntegerField(default=0, verbose_name='点赞数量')),
                ('associated', models.ForeignKey(help_text='associated_id to social_socialdynamic', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='social.socialdynamic', verbose_name='所评用户动态')),
                ('be_commented', models.ForeignKey(db_constraint=False, help_text='be_commented_id to usercenter_user', on_delete=django.db.models.deletion.CASCADE, related_name='be_commented', to=settings.AUTH_USER_MODEL, verbose_name='被评论者')),
                ('user', models.ForeignKey(db_constraint=False, help_text='user_id to usercenter_user', on_delete=django.db.models.deletion.CASCADE, related_name='commenter', to=settings.AUTH_USER_MODEL, verbose_name='评论者')),
            ],
            options={
                'verbose_name': 'Social: 评论',
                'verbose_name_plural': 'Social: 评论',
                'ordering': ['-comment_time'],
            },
        ),
        migrations.CreateModel(
            name='SocialPraise',
            fields=[
                ('id', utility.db_fields.TableNamePKField(blank=True, default=None, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('sys_id', models.IntegerField(db_index=True, default=1, verbose_name='系统ID')),
                ('org_id', models.IntegerField(db_index=True, default=1, verbose_name='组织ID')),
                ('biz_id', models.IntegerField(db_index=True, default=1, verbose_name='业务ID')),
                ('src_id', models.IntegerField(db_index=True, default=1, verbose_name='数据源ID')),
                ('thumbs_up_time', models.DateTimeField(auto_now_add=True, verbose_name='点赞时间')),
                ('be_thumbs_up', models.ForeignKey(db_constraint=False, help_text='be_thumbs_up_id to usercenter_user', on_delete=django.db.models.deletion.CASCADE, related_name='be_thumbs_up', to=settings.AUTH_USER_MODEL, verbose_name='被点赞者')),
                ('thumbs_up_dynamic', models.ForeignKey(db_constraint=False, help_text='thumbs_up_dynamic_id to social_socialdynamic', on_delete=django.db.models.deletion.CASCADE, related_name='thumbs_up', to='social.socialdynamic', verbose_name='所赞动态')),
                ('user', models.ForeignKey(db_constraint=False, help_text='user_id to usercenter_user', on_delete=django.db.models.deletion.CASCADE, related_name='thumbs_up', to=settings.AUTH_USER_MODEL, verbose_name='点赞者')),
            ],
            options={
                'verbose_name': 'Social: 点赞',
                'verbose_name_plural': 'Social: 点赞',
                'unique_together': {('user', 'thumbs_up_dynamic')},
            },
        ),
    ]
