# Generated by Django 3.2.11 on 2022-02-15 14:59

from django.db import migrations
import utility.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_auto_20220119_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialcomment',
            name='id',
            field=utility.db_fields.TableNamePKField('sc', serialize=False),
        ),
        migrations.AlterField(
            model_name='socialdynamic',
            name='id',
            field=utility.db_fields.TableNamePKField('sd', serialize=False),
        ),
        migrations.AlterField(
            model_name='socialpraise',
            name='id',
            field=utility.db_fields.TableNamePKField('sp', serialize=False),
        ),
    ]
